// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/data/events.content.ts
var eventContents = [
  {
    id: 1,
    date: "Samstag, 6. Dezember 2025",
    isoDate: "2025-12-06",
    weekday: "Sa",
    time: "20",
    location: "Sendesaal Bremen",
    title: "Fire! Orchestra",
    artist: "Mats Gustafsson & Ensemble",
    description: "Grootse improvisatie en energie door dit orkest met strijkers, blazers, ritmesectie en elektronica.",
    category: "jazz",
    moods: ["energetisch", "experimentell", "festlich"],
    imageKey: "fireOrchestra",
    externalTicketing: true
  },
  {
    id: 4,
    date: "Freitag, 13. Dezember 2025",
    isoDate: "2025-12-13",
    weekday: "Fr",
    time: "20",
    location: "Sendesaal Bremen",
    title: "Kammermusik Abend",
    artist: "Quatuor \xC9b\xE8ne",
    description: "Ein au\xDFergew\xF6hnliches Streichquartett pr\xE4sentiert Werke von Beethoven und Schubert in intimer Atmosph\xE4re.",
    category: "klassik",
    moods: ["intim", "virtuos", "romantisch"],
    imageKey: "kammermusik",
    externalTicketing: false
  },
  {
    id: 2,
    date: "Donnerstag, 9. Januar 2026",
    isoDate: "2026-01-09",
    weekday: "Do",
    time: "20",
    location: "Sendesaal Bremen",
    title: "Tingvall Trio",
    artist: "Martin Tingvall, Omar Rodriguez Calvo, J\xFCrgen Spiegel",
    description: "Nordischer Jazz trifft auf klassische Einfl\xFCsse \u2013 melodisch, virtuos und voller Emotionen.",
    category: "jazz",
    moods: ["intim", "virtuos", "romantisch"],
    imageKey: "tingvallTrio",
    externalTicketing: false
  },
  {
    id: 5,
    date: "Sonntag, 19. Januar 2026",
    isoDate: "2026-01-19",
    weekday: "So",
    time: "18",
    location: "Sendesaal Bremen",
    title: "Klavier Rezital",
    artist: "Igor Levit",
    description: "Der preisgekr\xF6nte Pianist spielt Bachs Goldberg-Variationen in einer unvergesslichen Interpretation.",
    category: "klassik",
    moods: ["virtuos", "meditativ", "intim"],
    imageKey: "klavierRezital",
    externalTicketing: false
  },
  {
    id: 3,
    date: "Freitag, 23. Januar 2026",
    isoDate: "2026-01-23",
    weekday: "Fr",
    time: "20",
    location: "Sendesaal Bremen",
    title: "Esbj\xF6rn Svensson Memorial",
    artist: "Dan Berglund & Magnus \xD6str\xF6m",
    description: "Ein Abend zu Ehren des legend\xE4ren schwedischen Pianisten mit seinen ehemaligen Bandkollegen.",
    category: "jazz",
    moods: ["intim", "romantisch", "meditativ"],
    imageKey: "esbjornMemorial",
    externalTicketing: true
  },
  {
    id: 6,
    date: "Samstag, 8. Februar 2026",
    isoDate: "2026-02-08",
    weekday: "Sa",
    time: "20",
    location: "Sendesaal Bremen",
    title: "Barocke Nacht",
    artist: "Concerto K\xF6ln",
    description: "Vivaldi, Bach und H\xE4ndel in authentischer Auff\xFChrungspraxis mit historischen Instrumenten.",
    category: "klassik",
    moods: ["festlich", "virtuos"],
    imageKey: "barockeNacht",
    externalTicketing: true
  },
  {
    id: 7,
    date: "Freitag, 20. Februar 2026",
    isoDate: "2026-02-20",
    weekday: "Fr",
    time: "20",
    location: "Sendesaal Bremen",
    title: "Nordic Voices",
    artist: "Ensemble Nordic Voices",
    description: "Skandinavische Vokalmusik von mittelalterlichen Hymnen bis zu zeitgen\xF6ssischen Kompositionen.",
    category: "klassik",
    moods: ["meditativ", "international", "intim"],
    imageKey: "kammermusik",
    externalTicketing: false
  },
  {
    id: 8,
    date: "Samstag, 7. M\xE4rz 2026",
    isoDate: "2026-03-07",
    weekday: "Sa",
    time: "20",
    location: "Sendesaal Bremen",
    title: "Anouar Brahem Quartet",
    artist: "Anouar Brahem, Fran\xE7ois Couturier, Klaus Gesing, Bj\xF6rn Meyer",
    description: "Arabische Oud-Tradition trifft auf europ\xE4ischen Jazz \u2013 eine einzigartige musikalische Begegnung.",
    category: "weltmusik",
    moods: ["international", "meditativ", "intim"],
    imageKey: "tingvallTrio",
    externalTicketing: true
  },
  {
    id: 9,
    date: "Donnerstag, 19. M\xE4rz 2026",
    isoDate: "2026-03-19",
    weekday: "Do",
    time: "20",
    location: "Sendesaal Bremen",
    title: "Portico Quartet",
    artist: "Portico Quartet",
    description: "Atmosph\xE4rische Klanglandschaften zwischen Jazz, Electronica und Minimalismus.",
    category: "experimentell",
    moods: ["experimentell", "meditativ"],
    imageKey: "esbjornMemorial",
    externalTicketing: false
  },
  {
    id: 10,
    date: "Samstag, 28. M\xE4rz 2026",
    isoDate: "2026-03-28",
    weekday: "Sa",
    time: "20",
    location: "Sendesaal Bremen",
    title: "H\xE9l\xE8ne Grimaud",
    artist: "H\xE9l\xE8ne Grimaud",
    description: "Die franz\xF6sische Starpianistin mit einem Programm von Brahms und Rachmaninow.",
    category: "klassik",
    moods: ["virtuos", "romantisch", "intim"],
    imageKey: "klavierRezital",
    externalTicketing: false
  },
  {
    id: 11,
    date: "Freitag, 10. April 2026",
    isoDate: "2026-04-10",
    weekday: "Fr",
    time: "20",
    location: "Sendesaal Bremen",
    title: "Shai Maestro Trio",
    artist: "Shai Maestro, Jorge Roeder, Ofri Nehemya",
    description: "Israelischer Jazz voller Lyrik und Intensit\xE4t \u2013 eines der aufregendsten Trios der Szene.",
    category: "jazz",
    moods: ["intim", "virtuos", "international"],
    imageKey: "fireOrchestra",
    externalTicketing: false
  },
  {
    id: 12,
    date: "Samstag, 25. April 2026",
    isoDate: "2026-04-25",
    weekday: "Sa",
    time: "19",
    location: "Sendesaal Bremen",
    title: "Klassik trifft Flamenco",
    artist: "Dorantes & Renaud Capu\xE7on",
    description: "Eine faszinierende Verschmelzung von klassischer Violine und andalusischem Klavier.",
    category: "weltmusik",
    moods: ["festlich", "international", "virtuos"],
    imageKey: "barockeNacht",
    externalTicketing: true
  }
];

// src/data/news.content.ts
var newsContents = [
  {
    id: "fire-orchestra-zusatztermin",
    date: "2026-05-14",
    category: "Konzert",
    title: "Fire! Orchestra: Zusatztermin im Sendesaal Bremen",
    excerpt: "Nach kurzer Verkaufszeit ausverkauft \u2013 Mats Gustafsson und sein Ensemble kommen f\xFCr einen zweiten Abend zur\xFCck in den Sendesaal.",
    href: "/aktuelles/fire-orchestra-zusatztermin",
    imageKey: "fireOrchestra",
    lead: "Die Resonanz war \xFCberw\xE4ltigend: Innerhalb weniger Tage war das Konzert des Fire! Orchestra restlos ausverkauft. Auf vielfachen Wunsch \xF6ffnen wir nun einen Zusatztermin am Folgeabend.",
    body: [
      "Mats Gustafsson und sein \xFCber zwanzigk\xF6pfiges Ensemble verbinden orchestralen Free Jazz mit elektronischen Texturen und kompromissloser Improvisation. Die einzigartige Akustik des Sendesaals macht dieses Klangerlebnis besonders intensiv erfahrbar.",
      "Der Zusatztermin findet am Sonntag, dem 7. Dezember 2025 statt. Tickets sind ab sofort \xFCber unseren Vorverkaufspartner sowie an der Abendkasse erh\xE4ltlich. F\xFCr Inhaberinnen und Inhaber der Sendesaal-Card gilt das \xFCbliche Vorkaufsrecht.",
      "Wir empfehlen, fr\xFChzeitig zu buchen \u2013 auch der zweite Abend st\xF6\xDFt bereits auf gro\xDFes Interesse. Das Konzert beginnt um 20 Uhr, Einlass ist ab 19 Uhr."
    ]
  },
  {
    id: "saison-2026-programm",
    date: "2026-04-28",
    category: "Programm",
    title: "Saison 2026/27: Das neue Programm ist da",
    excerpt: "\xDCber 60 Konzerte zwischen Klassik, Jazz und Neuer Musik. Ein erster Blick auf die H\xF6hepunkte der kommenden Spielzeit.",
    href: "/aktuelles/saison-2026-programm",
    imageKey: "kammermusik",
    lead: "Mit \xFCber 60 Konzerten setzt die Saison 2026/27 ein klares Bekenntnis zur Vielfalt: Klassische Kammermusik, internationaler Jazz und neue Musik treffen in unserem Saal aufeinander.",
    body: [
      "Zu den H\xF6hepunkten z\xE4hlen Residenzen renommierter Ensembles, Wiederbegegnungen mit langj\xE4hrigen Wegbegleiterinnen und Wegbegleitern sowie zahlreiche Deb\xFCts junger Stimmen, die hier erstmals zu erleben sein werden.",
      "Neu im Programm ist eine Reihe kuratierter Themenwochenenden, die einzelne Komponistinnen, Stilrichtungen und Aufnahmeprojekte in den Mittelpunkt r\xFCcken. Begleitend bieten wir Werkeinf\xFChrungen, K\xFCnstlergespr\xE4che und offene Proben an.",
      "Das vollst\xE4ndige Saisonheft liegt ab sofort im Foyer aus und steht in unserem Programm-Bereich als digitale Ausgabe zur Verf\xFCgung. Der Vorverkauf f\xFCr Mitglieder startet am 5. Mai, f\xFCr alle weiteren Interessierten am 12. Mai."
    ]
  },
  {
    id: "echo-klassik-auszeichnung",
    date: "2026-03-12",
    category: "Presse",
    title: "Aufnahme aus dem Sendesaal mit ECHO Klassik ausgezeichnet",
    excerpt: "Die im Sendesaal Bremen entstandene Einspielung des Quatuor \xC9b\xE8ne wurde von der Jury als beste Kammermusikproduktion gew\xFCrdigt.",
    href: "/aktuelles/echo-klassik-auszeichnung",
    imageKey: "klavierRezital",
    lead: "Eine besondere Anerkennung f\xFCr die Arbeit unseres Hauses: Die im Sendesaal entstandene Einspielung des Quatuor \xC9b\xE8ne ist mit dem ECHO Klassik in der Kategorie \u201EBeste Kammermusikproduktion\u201C ausgezeichnet worden.",
    body: [
      "Die Jury w\xFCrdigt die au\xDFergew\xF6hnliche Klangqualit\xE4t der Aufnahme und hebt insbesondere die R\xE4umlichkeit und Transparenz hervor \u2013 Eigenschaften, die seit Jahrzehnten den Ruf der Sendesaal-Akustik pr\xE4gen.",
      "Verantwortlich f\xFCr die Produktion zeichnet unser Tonmeister-Team in enger Zusammenarbeit mit dem Label und dem Quartett. Die Aufnahmen entstanden \xFCber mehrere Sessions im Fr\xFChjahr 2025 und umfassen Werke von Beethoven und Schubert.",
      "Die ausgezeichnete Produktion ist im Handel sowie auf den g\xE4ngigen Streaming-Plattformen verf\xFCgbar. Wir gratulieren allen Beteiligten herzlich zu dieser besonderen W\xFCrdigung."
    ]
  },
  {
    id: "tag-der-offenen-tuer",
    date: "2026-02-20",
    category: "Saison",
    title: "Tag der offenen T\xFCr: Akustik zum Anfassen",
    excerpt: "F\xFChrungen durch den historischen Saal, Live-Demonstrationen der Aufnahmetechnik und Gespr\xE4che mit Tonmeisterinnen und Tonmeistern.",
    href: "/aktuelles/tag-der-offenen-tuer",
    imageKey: "experimental",
    lead: "Einmal im Jahr \xF6ffnen wir alle T\xFCren: Am Tag der offenen T\xFCr l\xE4dt der Sendesaal Bremen dazu ein, das Haus, seine Geschichte und seine Akustik aus n\xE4chster N\xE4he zu erleben.",
    body: [
      "Auf dem Programm stehen st\xFCndliche F\xFChrungen durch den gro\xDFen Saal und die Regie, Live-Demonstrationen aktueller Aufnahmetechnik sowie Gespr\xE4che mit Tonmeisterinnen, Tonmeistern und Musikerinnen und Musikern, die regelm\xE4\xDFig hier zu Gast sind.",
      "F\xFCr Familien gibt es ein eigenes Programm: Kinder d\xFCrfen Mikrofone ausprobieren, eigene Kl\xE4nge aufnehmen und gemeinsam mit unseren Mitarbeitenden ein kleines H\xF6rst\xFCck gestalten. Im Foyer sorgen Speisen und Getr\xE4nke f\xFCr das leibliche Wohl.",
      "Der Eintritt ist frei, eine Anmeldung ist nicht erforderlich. Wir freuen uns auf einen Tag voller Begegnungen rund um Klang, Raum und Musik."
    ]
  }
];

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "Konzerte auflisten",
  description: "Listet die Konzerte und Veranstaltungen im Sendesaal Bremen. Optional filterbar nach Kategorie und Suchbegriff.",
  inputSchema: {
    category: z.enum(["jazz", "klassik", "weltmusik", "experimentell"]).optional().describe("Nur Veranstaltungen dieser Kategorie."),
    query: z.string().optional().describe("Freitextsuche in Titel, K\xFCnstler und Beschreibung."),
    limit: z.number().int().optional().describe("Maximale Anzahl Ergebnisse (Standard 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, query, limit }) => {
    const q = query?.trim().toLowerCase();
    const items = eventContents.filter((e) => category ? e.category === category : true).filter(
      (e) => q ? [e.title, e.artist, e.description, e.category].join(" ").toLowerCase().includes(q) : true
    ).slice(0, Math.max(1, Math.min(limit ?? 20, 100)));
    if (items.length === 0) {
      return { content: [{ type: "text", text: "Keine passenden Veranstaltungen gefunden." }] };
    }
    return {
      content: [
        {
          type: "text",
          text: items.map(
            (e) => `#${e.id} ${e.title} \u2014 ${e.artist}
${e.date}, ${e.time} Uhr, ${e.location}
Kategorie: ${e.category}
${e.description}`
          ).join("\n\n")
        }
      ],
      structuredContent: { events: items }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Konzertdetails abrufen",
  description: "Liefert alle Details zu einer Veranstaltung im Sendesaal Bremen anhand ihrer ID.",
  inputSchema: { id: z2.number().int().describe("Die Veranstaltungs-ID aus list_events.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const event = eventContents.find((e) => e.id === id);
    if (!event) throw new ToolError(`Keine Veranstaltung mit der ID ${id} gefunden.`);
    return {
      content: [
        {
          type: "text",
          text: [
            `${event.title} \u2014 ${event.artist}`,
            `${event.date} (${event.weekday}), ${event.time} Uhr`,
            `Ort: ${event.location}`,
            `Kategorie: ${event.category}`,
            `Stimmungen: ${event.moods.join(", ")}`,
            `Tickets: ${event.externalTicketing ? "\xFCber externen Vorverkaufspartner" : "\xFCber den Sendesaal"}`,
            "",
            event.description
          ].join("\n")
        }
      ],
      structuredContent: { event }
    };
  }
});

// src/lib/mcp/tools/list-news.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_news_default = defineTool3({
  name: "list_news",
  title: "Aktuelles auflisten",
  description: "Listet die aktuellen Nachrichten und Ank\xFCndigungen des Sendesaals Bremen, neueste zuerst.",
  inputSchema: {
    limit: z3.number().int().optional().describe("Maximale Anzahl Ergebnisse (Standard 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ limit }) => {
    const items = [...newsContents].sort((a, b) => b.date.localeCompare(a.date)).slice(0, Math.max(1, Math.min(limit ?? 10, 50)));
    return {
      content: [
        {
          type: "text",
          text: items.map((n) => `${n.date} \xB7 ${n.category}
${n.title}
${n.excerpt}
Slug: ${n.id}`).join("\n\n")
        }
      ],
      structuredContent: { news: items }
    };
  }
});

// src/lib/mcp/tools/get-news-article.ts
import { defineTool as defineTool4, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var get_news_article_default = defineTool4({
  name: "get_news_article",
  title: "News-Beitrag abrufen",
  description: "Liefert den vollst\xE4ndigen Text eines Aktuelles-Beitrags anhand seines Slugs.",
  inputSchema: { slug: z4.string().describe("Der Slug des Beitrags aus list_news.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const article = newsContents.find((n) => n.id === slug.trim());
    if (!article) throw new ToolError2(`Kein Beitrag mit dem Slug "${slug}" gefunden.`);
    return {
      content: [
        {
          type: "text",
          text: [
            article.title,
            `${article.date} \xB7 ${article.category}`,
            "",
            article.lead ?? article.excerpt,
            "",
            ...article.body ?? []
          ].join("\n")
        }
      ],
      structuredContent: { article }
    };
  }
});

// src/lib/mcp/tools/search-faq.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";

// src/data/faq.ts
var faqItems = [
  {
    id: "abendkasse",
    question: "Gibt es eine Abendkasse?",
    answer: "Ja, sofern noch Karten verf\xFCgbar sind, \xF6ffnet unsere Abendkasse 45 Minuten vor Veranstaltungsbeginn. Wir empfehlen jedoch den Vorverkauf, da viele Konzerte ausverkauft sind."
  },
  {
    id: "barrierefrei",
    question: "Ist der Sendesaal barrierefrei?",
    answer: "Der Sendesaal ist barrierefrei zug\xE4nglich. Es gibt Rollstuhlpl\xE4tze im Parkett sowie eine behindertengerechte Toilette. Bitte informieren Sie uns bei der Buchung \xFCber Ihre Bed\xFCrfnisse."
  },
  {
    id: "garderobe",
    question: "Wie sind die \xD6ffnungszeiten der Garderobe?",
    answer: "Die Garderobe \xF6ffnet 45 Minuten vor Konzertbeginn und bleibt bis 30 Minuten nach Ende der Veranstaltung ge\xF6ffnet. Die Garderobennutzung ist kostenfrei."
  },
  {
    id: "ermaessigung",
    question: "Gibt es Erm\xE4\xDFigungen f\xFCr Studenten?",
    answer: "Ja, Studierende erhalten gegen Vorlage eines g\xFCltigen Studierendenausweises eine Erm\xE4\xDFigung von 20% auf regul\xE4re Eintrittspreise. Diese Erm\xE4\xDFigung gilt nicht f\xFCr Sonderveranstaltungen."
  },
  {
    id: "umtausch",
    question: "Kann ich meine Tickets umtauschen oder stornieren?",
    answer: "Ein Umtausch oder eine Erstattung ist leider nicht m\xF6glich. Bei Ausfall einer Veranstaltung erhalten Sie selbstverst\xE4ndlich den vollen Kaufpreis zur\xFCck."
  }
];

// src/lib/mcp/tools/search-faq.ts
var search_faq_default = defineTool5({
  name: "search_faq",
  title: "FAQ durchsuchen",
  description: "Beantwortet h\xE4ufige Besucherfragen zum Sendesaal Bremen (Abendkasse, Barrierefreiheit, Erm\xE4\xDFigungen, Garderobe usw.).",
  inputSchema: {
    query: z5.string().optional().describe("Suchbegriff. Ohne Angabe werden alle Fragen geliefert.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query }) => {
    const q = query?.trim().toLowerCase();
    const items = q ? faqItems.filter((f) => `${f.question} ${f.answer}`.toLowerCase().includes(q)) : faqItems;
    if (items.length === 0) {
      return {
        content: [
          {
            type: "text",
            text: "Dazu gibt es keinen FAQ-Eintrag. Bitte direkt beim Sendesaal Bremen anfragen."
          }
        ]
      };
    }
    return {
      content: [
        { type: "text", text: items.map((f) => `${f.question}
${f.answer}`).join("\n\n") }
      ],
      structuredContent: { faq: items }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "remix-of-sendesaal-resonance-redesign-v1",
  title: "Remix of Sendesaal Resonance Redesign v1",
  version: "0.1.0",
  instructions: "\xD6ffentliche Inhalte des Sendesaals Bremen: `list_events` und `get_event` f\xFCr das Konzertprogramm, `list_news` und `get_news_article` f\xFCr Aktuelles, `search_faq` f\xFCr Besucherfragen.",
  tools: [list_events_default, get_event_default, list_news_default, get_news_article_default, search_faq_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
